<?php

return [
    'nav-back'          => 'Trở lại',
    'nav-new'           => 'Thư mục mới',
    'nav-upload'        => 'Tải lên',
    'nav-thumbnails'    => 'Hình thu nhỏ',
    'nav-list'          => 'Danh sách',
    'nav-sort'          => 'Sắp xếp',
    'nav-sort-alphabetic'=> 'Sắp xếp theo Alphabets',
    'nav-sort-time'     => 'Sắp xếp theo thời gian',

    'menu-rename'       => 'Đổi tên',
    'menu-delete'       => 'Xóa',
    'menu-view'         => 'Xem trước',
    'menu-download'     => 'Tải xuống',
    'menu-resize'       => 'Thay đổi kích thước',
    'menu-crop'         => 'Cắt ảnh',

    'title-page'        => 'Quản lý Tệp',
    'title-panel'       => 'By Trung Lê',
    'title-upload'      => 'Tải tệp lên',
    'title-view'        => 'Xem tệp',
    'title-root'        => 'Thư mục',
    'title-shares'      => 'Shared',
    'title-item'        => 'Item',
    'title-size'        => 'Size',
    'title-type'        => 'Loại',
    'title-modified'    => 'Sửa đổi',
    'title-action'      => 'Tác vụ',

    'type-folder'       => 'Thư mục',

    'message-empty'     => 'Thư mục rỗng.',
    'message-choose'    => 'Chọn tệp',
    'message-delete'    => 'Bạn muốn xóa tệp này?',
    'message-name'      => 'Tên thư mục:',
    'message-rename'    => 'Đổi tên thành:',
    'message-extension_not_found' => 'Vui lòng cài đặt tiện ích gd hoặc imagick để có thể cắt, thay đổi kích thước, tạo hình thu nhỏ!',

    'error-rename'      => 'Tên tệp đã được sử dụng!',
    'error-file-name'   => 'Tên tệp không thể rỗng!',
    'error-file-empty'  => 'Bạn phải chọn tệp!',
    'error-file-exist'  => 'Một tệp có tên này đã tồn tại!',
    'error-file-size'   => 'Kích thước tệp vượt quá giới hạn máy chủ! (maximum size: :max)',
    'error-delete-folder'=> 'Bạn không thể xóa thư mục này vì nó không phải là trống!',
    'error-folder-name' => 'Tên thư mục không thể để trống!',
    'error-folder-exist'=> 'Thư mục có tên này đã tồn tại!',
    'error-folder-alnum'=> 'Chỉ cho phép tên thư mục chữ và số!',
    'error-folder-not-found'=> 'Không tìm thấy thư mục! (:folder)',
    'error-mime'        => 'Unexpected MimeType: ',
    'error-size'        => 'Over limit size:',
    'error-instance'    => 'Tệp được tải lên phải là một cá thể của UploadedFile',
    'error-invalid'     => 'Yêu cầu tải lên không hợp lệ',
    'error-other'       => 'Đã xảy ra lỗi: ',
    'error-too-large'   => 'Yêu cầu đối tượng quá lớn!',

    'btn-upload'        => 'Tải lên(s)',
    'btn-uploading'     => 'Tải lên...',
    'btn-close'         => 'Đóng',
    'btn-crop'          => 'Crop',
    'btn-copy-crop'     => 'Copy & Crop',
    'btn-cancel'        => 'Cancel',
    'btn-resize'        => 'Resize',

    'resize-ratio'      => 'Ratio:',
    'resize-scaled'     => 'Image scaled:',
    'resize-true'       => 'Yes',
    'resize-old-height' => 'Original Height:',
    'resize-old-width'  => 'Original Width:',
    'resize-new-height' => 'Height:',
    'resize-new-width'  => 'Width:',

    'locale-bootbox'    => 'en',
];
